---
title: "De panes, perros y mapas"
date: 2018-05-08
---


title: De panes, perros y mapas
email: clauavila.sch@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A blog about random things that I like. Mostly sourdough bread, maps stuff and some dogs photos. 
  Just learnign how towork my way in GitHub.

# social links
twitter_username: @clauavilas
github_username: clauavila

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
